/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_flysnow_app_example132_HelloWorld */

#ifndef _Included_org_flysnow_app_example132_HelloWorld
#define _Included_org_flysnow_app_example132_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_flysnow_app_example132_HelloWorld
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_flysnow_app_example132_HelloWorld_getHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
